#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
date >> $SCRIPT_DIR/response.log;
python3 $SCRIPT_DIR/main.py $SCRIPT_DIR 1>> $SCRIPT_DIR/response.log 2>> $SCRIPT_DIR/error.log;
echo "Survey auto-filled for today!"