#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# check if user exists
if [[ -e $SCRIPT_DIR/user_info.txt && -e $SCRIPT_DIR/duotoken.hotp ]]; then

  # check if crontab exists
  crontab_exists=$(crontab -l | grep -e "$SCRIPT_DIR/cronjob")
  echo $crontab_exists
  # && crontab_exists != *"no crontab"* 
  if [[ -n $crontab_exists ]]; then
    echo "UCLA CAT already scheduled!"
  else
    # run once
    # python3 $SCRIPT_DIR/main.py $SCRIPT_DIR 1>> $SCRIPT_DIR/response.log 2>> $SCRIPT_DIR/error.log
    # echo "Survey auto-filled for today!"

    # create crontab
    crontab -l > ucla_cat_cron
    echo "0 0 * * * $SCRIPT_DIR/cronjob" >> ucla_cat_cron
    crontab ucla_cat_cron
    rm ucla_cat_cron

    echo "Scheduled UCLA CAT to run every day at midnight!"
  fi
else
  echo "User not registered...Click and run autofill once to register a new user"
fi