#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo SCRIPT_DIR

crontab -l > ucla_cat_cron
echo "0 0 * * * export PYTHONPATH=/opt/homebrew/lib/python3.10/site-packages; date; python3 $SCRIPT_DIR/main.py $SCRIPT_DIR 1>> $SCRIPT_DIR/response.log 2>> $SCRIPT_DIR/error.log" >> ucla_cat_cron
crontab ucla_cat_cron
rm ucla_cat_cron

echo Scheduled UCLA CAT to run every day at midnight!