#!/usr/bin/env bash

# echo Running UCLA CAT...
# python3 $PWD/main.py $PWD 1>> $PWD/response.log 2>> $PWD/error.log

date >> $PWD/response.log

crontab -l > ucla_cat_cron
echo "* * * * * export PYTHONPATH=/opt/homebrew/lib/python3.10/site-packages; date; python3 $PWD/main.py $PWD 1>> $PWD/response.log 2>> $PWD/error.log" >> ucla_cat_cron
crontab ucla_cat_cron
rm ucla_cat_cron

echo Scheduled UCLA CAT to run every day at midnight!